services:
  - type: web
    name: doc-developer
    runtime: static
    repo: https://github.com/caido/doc-developer.git
    branch: main
    buildCommand: make build-release
    staticPublishPath: ./.vitepress/dist
    pullRequestPreviewsEnabled: true
    routes:
      - type: rewrite
        source: /stats/script.js
        destination: https://plausible.io/js/plausible.js
      - type: rewrite
        source: /stats/event
        destination: https://plausible.io/api/event
      - type: redirect
        source: /concepts/essentials/plugins/
        destination: /guides/
      - type: redirect
        source: /concepts/essentials/plugins/frontend.html
        destination: /guides/
      - type: redirect
        source: /concepts/essentials/plugins/backend.html
        destination: /guides/
    domains:
      - developer.caido.io
    envVars:
      - key: SKIP_INSTALL_DEPS
        value: true
